Fima/Fima/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Fima import settings
urlpatterns = [
    path('admin/', admin.site.	urls),
    path('',views.index,name='index'),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fima/app1/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
app_name='app1'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('special',views.special,name='special'),
    path('logout',views.user_logout,name='logout'),
    path('search',views.user_search,name='search'),
    path('transaction',views.make_transaction,name='transaction'),
    path('profile',views.user_profile,name='profile'),
    path('viewprofile',views.user_profile_view,name='viewprofile'),
    path('notification',views.show_notification,name='notification'),
    path('delete',views.delete_account,name='delete'),
]

Fima/app1/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.validators import RegexValidator
# Create your models here.

User._meta.get_field('email')._unique = True
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	dob=models.DateField()
	Categories =(("Male","Male"),("Female","Female"))
	gender=models.CharField(max_length=10 , choices=Categories)
	name=models.CharField(max_length=500,default='Your Name')		
	profile_pic = models.ImageField(upload_to='app1/profile_pics',blank=True,default='app1/profile_pics/default.png')
	phone_number = models.CharField(max_length=10,blank=True,validators=[RegexValidator('^[0-9]{10}$',message="Invalid Number")])
	user_address=models.CharField(max_length=500,blank=True)
	def __str__(self):
  		return self.user.username

class CurrentTransaction(models.Model):
	user_id1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related1')
	user_id2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related2')
	tdate=models.DateField()
	amount=models.IntegerField()
	lent=models.CharField(max_length=500)
	borrowed=models.CharField(max_length=500)
	desc=models.CharField(max_length=500)

class Friends(models.Model):
	user_id1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related1')
	user_id2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related2')
	class Meta:
		unique_together = ['user_id1', 'user_id2']

class TransactionHistory(models.Model):
	user_id1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related1')
	user_id2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_related2')
	date=models.DateField()
	Amount=models.IntegerField()
	lent=models.CharField(max_length=500)
	borrowed=models.CharField(max_length=500)
	Desc=models.CharField(max_length=500)

class OldNotification(models.Model):
	user_id=models.ForeignKey(User,on_delete=models.CASCADE)
	desc=models.CharField(max_length=500)
	date=models.DateField()

class NewNotification(models.Model):
	user_id=models.ForeignKey(User,on_delete=models.CASCADE)
	desc=models.CharField(max_length=500)
	date=models.DateField(default=datetime.date.today)


#yes

Fima/app1/forms.py
from django import forms
from app1.models import UserProfileInfo
from django.contrib.auth.models import User
from app1.models import CurrentTransaction

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model=User
		fields=('email','password')
		widgets = {
			'email': forms.TextInput(attrs={'id':'email','class': 'text_field'}),
			'password':forms.PasswordInput(attrs={'id':'password','class':'text_field'})
			}

class UserProfileInfoForm(forms.ModelForm):
	 class Meta():
		 model = UserProfileInfo
		 fields = ('name','gender','dob','phone_number','user_address','profile_pic')
		 widgets = {
			'name': forms.TextInput(attrs={'id':'name','class': 'text_field'}),
			'phone_number': forms.TextInput(attrs={'id':'phone_number','class': 'text_field'}),
			'user_address': forms.TextInput(attrs={'id':'user_address','class': 'text_field'}),
			'dob': forms.TextInput(attrs={'id':'dob','class': 'text_field' ,'placeholder': 'MM/DD/YYYY'}),
			
			}

class TransactionForm(forms.Form):
	Amount=forms.IntegerField(max_value=100000, label='Amount',widget=forms.NumberInput(attrs={'id':'Amount','class':'text_field'}))
	Action=forms.ChoiceField(choices=[('Lent','Lent'),('Borrowed','Borrowed')])
	Desc=forms.CharField(label='Description',max_length=500,widget=forms.TextInput(attrs={'id':'Desc','class':'text_field'}))

class UpdateProfileForm(forms.Form):
	name = forms.CharField(max_length=50 , widget=forms.TextInput(attrs={'id':'name','class':'text_field'}) )
	phone = forms.CharField(max_length=10 , widget=forms.TextInput(attrs={'id':'phone','class':'text_field'}) )
	address = forms.CharField(max_length=300 , widget=forms.TextInput(attrs={'id':'address','class':'text_field'}) )
	old_password = forms.CharField(label='Old password',widget=forms.PasswordInput(attrs={'id':'old_password','class':'text_field'}))
	new_password = forms.CharField(label='New password',widget=forms.PasswordInput(attrs={'id':'new_password','class':'text_field'}))
	conf_password = forms.CharField(label='Confirm password',widget=forms.PasswordInput(attrs={'id':'conf_password','class':'text_field'}))

Fima/app1/views.py
from django.shortcuts import render
from app1.forms import UserForm,UserProfileInfoForm,UpdateProfileForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from app1.models import CurrentTransaction,Friends,UserProfileInfo,OldNotification,NewNotification
from django.contrib.auth.models import User

from app1.forms import TransactionForm
from django.utils import timezone
from django.contrib.auth.hashers import check_password
import copy
from datetime import date
from django.contrib.auth.signals import user_logged_out
from django.dispatch import receiver
from django.contrib import messages

# Create your views here.

is_delete_message=False
is_update_message=False

@receiver(user_logged_out)
def on_user_logged_out(sender, request, **kwargs):
	if(is_update_message):
		messages.add_message(request, messages.INFO, 'Account Details Updated SuccesFully, Login Again')
	
	elif(is_delete_message):
		messages.add_message(request, messages.INFO, 'Account Deleted SuccesFully, Good Bye!')

	else:
		messages.add_message(request, messages.INFO, 'You Have Logged Out SuccesFully, Good Bye!')


def index(request):
	return render(request,'app1/index.html')

@login_required
def special(request):
	return HttpResponse("You Are logged in !")

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def register(request):
	registered=False
	error_s = ""
	if(request.method=='POST'):
		user_form=UserForm(data=request.POST)
		profile_form=UserProfileInfoForm(data=request.POST)

		if(user_form.is_valid() and profile_form.is_valid()):
			user=user_form.save(commit=False)
			user.set_password(user.password)
			user.username=user.email
			user.save()
			profile=profile_form.save(commit=False)
			profile.user=user

			# Check if they provided a profile picture
			if 'profile_pic' in request.FILES:
				print('found it')
				# If yes, then grab it from the POST form reply
				profile.profile_pic = request.FILES['profile_pic']

			# Now save model
			profile.save()
			registered=True

		else:
			print(user_form.errors,profile_form.errors)
			error_s1=	str(user_form.errors)
			error_s2 = str(profile_form.errors)
			user_form=UserForm()
			return render(request,'app1/registration.html',{'error_s1':error_s1,'error_s2':error_s2,'user_form':user_form,
						   'profile_form':profile_form})
			
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()
	return render(request,'app1/registration.html',
						  {'user_form':user_form,
						   'profile_form':profile_form,
						   'registered':registered})

def user_login(request):
	global is_check_notofication
	global is_delete_message
	global is_update_message
	is_check_notofication=False
	is_delete_message=False
	is_update_message=False
	if(request.method=="POST"):
		username=request.POST.get('username')
		password=request.POST.get('password')
		user=authenticate(username=username,password=password)
		if(user):
			if(user.is_active):
				login(request,user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("Your account was inactive.")

		else:
			print("Someone tried to login and failed.")
			print("They used username: {} and password: {}".format(username,password))
			return render(request, 'app1/login.html', {'failed_login':True})
	else:
		return render(request, 'app1/login.html', {})

add_friend=None
@login_required
def user_search(request):
	global add_friend
	if(request.method=='POST'):
		print("I am in if 1")
		query=request.POST.get('q')
		# print(query)
		cur_user=request.user
		# print(request.POST.get('add'),add_friend)
		if(request.POST.get('add') and add_friend):
			f1=Friends()
			f1.user_id1=User.objects.get(id=request.user.id)
			f1.user_id2=User.objects.get(id=add_friend.id)
			f1.save()
			f2=Friends()
			f2.user_id2=User.objects.get(id=request.user.id)
			f2.user_id1=User.objects.get(id=add_friend.id)
			f2.save()
			message1 =request.user.email+" has added you as friend on "+str(date.today())
			message_curr="You Have added " + add_friend.email + " as your friend on " + str(date.today())
			add_notification(add_friend,message1)
			add_notification(request.user,message_curr)
			return render(request, 'app1/search.html',{'success':True} )
		elif(query is not None):
			is_exist=False
			result=User.objects.filter(email=query)
			if(result.exists() and result[0].username!=request.user.username):
				# print(request.user.username)
				is_friend=False
				is_friend_query=Friends.objects.filter(user_id1=request.user.id,
					user_id2=result[0].id)
				if(is_friend_query.exists()):
					is_friend=True
				else:
					add_friend=result[0]
				return render(request,'app1/search.html',{'result':result[0],'is_friend':is_friend})
			else:
				return render(request,'app1/search.html')

		else:
			return render(request,'app1/search.html')
	else:
		print("I am in else 1")
		return render(request,'app1/search.html')




passed_email=None
@login_required
def make_transaction(request):
	global passed_email
	if(request.method=='POST'):
		print(request.POST)
		if('show' in request.POST):
			form=TransactionForm()
			passed_email = request.POST.get('friend_id')
			print("Show"+passed_email)
			return render(request,'app1/transaction.html',{"passed_email":passed_email,'form':form})

		else:
			print("Add"+passed_email)
			form=TransactionForm(request.POST)
			is_click=True
			to_user=User.objects.filter(email=passed_email)
			if(form.is_valid()):
				print("Validation Success")
				action=form.cleaned_data['Action']
				amount=form.cleaned_data['Amount']
				desc=form.cleaned_data['Desc']
				if(to_user.exists()):
					to_friend=Friends.objects.filter(user_id1=request.user.id,
							user_id2=to_user[0].id)
					if(to_friend.exists()):
						new_transaction=CurrentTransaction()
						print("action="+str(action))
						print(UserProfileInfo.objects.filter(user_id=
								to_friend[0].user_id2.id))
						if(action=='Lent'):
							new_transaction.user_id1=request.user
							new_transaction.user_id2=User.objects.get(id=to_friend[0].user_id2.id)
							new_transaction.lent=UserProfileInfo.objects.filter(user=
								request.user)[0].name
							new_transaction.borrowed=UserProfileInfo.objects.filter(user=
								to_friend[0].user_id2)[0].name
							
							message_curr ="You Have Lent Rs "+str(amount)+" to "+to_friend[0].user_id2.email+" on "+str(date.today())
							message1="You Have Borrowed Rs "+str(amount)+" from "+request.user.email +" on "+str(date.today())
							add_notification(to_friend[0].user_id2,message1)
							add_notification(request.user,message_curr)
							
						else:
							new_transaction.user_id2=request.user
							new_transaction.user_id1=User.objects.get(id=to_friend[0].user_id2.id)
							new_transaction.borrowed=UserProfileInfo.objects.filter(user=
								request.user)[0].name
							new_transaction.lent=UserProfileInfo.objects.filter(user=
								to_friend[0].user_id2)[0].name

							message1 ="You Have Lent Rs"+str(amount)+" to "+request.user.email+" on "+str(date.today())
							message_curr="You Have Borrowed Rs"+str(amount)+" from "+to_friend[0].user_id2.email+" on "+str(date.today())
							add_notification(to_friend[0].user_id2,message1)
							add_notification(request.user,message_curr)

						new_transaction.amount=amount
						new_transaction.desc=desc
						new_transaction.tdate=timezone.now()
						new_transaction.save()
						return render(request,'app1/transaction.html',{'to_friend':to_friend,'form':form,
						"passed_email":passed_email})

					else:
						return render(request,'app1/transaction.html',{'to_user':to_user,'form':form,
						"passed_email":passed_email}) 

				else:
					print("Validation Failed")
					return HttpResponse("invalid Form")

			else:
				return render(request,'app1/transaction.html',{'form':form,"passed_email":passed_email})

	else:
		form=TransactionForm()
		return render(request,'app1/transaction.html',{'form':form,"passed_email":passed_email})





@login_required
def user_profile_view(request):
	user_info=UserProfileInfo.objects.filter(user=request.user)[0]
	return render(request,"app1/show_profile.html",{"user":request.user,"user_info":user_info})







@login_required
def user_profile(request):
	global is_update_message
	if(request.method=='POST'):
		form=UpdateProfileForm(request.POST)
		is_clicked=True
		if(form.is_valid()):
			print("form is valid")
			new_name=form.cleaned_data['name']
			new_phone_number=form.cleaned_data['phone']
			new_user_address=form.cleaned_data['address']
			old_password=form.cleaned_data['old_password']
		
			if(check_password(old_password,request.user.password)):
				print("Check Password Success")
				new_password=form.cleaned_data['new_password']
				conf_password=form.cleaned_data['conf_password']
				is_update=False
				if(new_password==conf_password):
					is_update=True
					new_user=request.user
					new_user_profile=UserProfileInfo.objects.filter(user=request.user)[0]
					new_user.set_password(new_password)
					new_user_profile.name=new_name
					new_user_profile.phone_number=new_phone_number
					new_user_profile.user_address=new_user_address
					new_user.save()
					new_user_profile.save()
					is_update_message=True
					return user_logout(request)
				print(is_update)
				return render(request,'app1/profile.html',{'is_update':is_update,'form':form})

			return render(request,'app1/profile.html',{'is_clicked':is_clicked,'form':form})
		
		else:
			ValidationError(_('Invalid value'), code='invalid')
	else:
		form=UpdateProfileForm(initial={'name': UserProfileInfo.objects.filter(user=request.user)[0].name,
		'phone':UserProfileInfo.objects.filter(user=request.user)[0].phone_number,
		'address':UserProfileInfo.objects.filter(user=request.user)[0].user_address})
		return render(request,'app1/profile.html',{'form':form})

Fima/templates/app1/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  
</head>
  <body>
    <!-- {% debug %} -->
    {% block foo %}
     {% include "app2/main_index.html" %}
    {% endblock %}

    
     <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Fima/templates/app1/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <title>Login</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- remove this for good font -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- remove this for good font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel = 'stylesheet' href ="{% static "css/user_profile.css" %}"/> 
    <link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 

    <style>
    .main_heading{
    color:rgb(255, 0, 0);
    margin-left:80px;
    margin-top: 100px;
    font-family: Advent Pro;
    font-size: 50px;
  }
  .text_field{
        font-size:30px;
        color:rgb(50, 51, 42);
        font-family: Advent Pro;
        margin-left: 30px;
        display:table-cell;

      }
      .text_label{
        font-size:40px;
        color:rgb(62, 63, 54);
        margin-bottom: 20px;
        font-family: Advent Pro;
        display:table-cell;

      }
      .submitbutton{
        margin-left:00px;
        width:240px;
        height:80px;
        padding-top: 10px;
        font-family:  Advent Pro;
        font-size:30px;
        font-weight: bold;
      }

      .main_heading{
      color:black;
      margin-left:430px;
      margin-top: 100px;
      font-family: Advent Pro;
      font-size: 50px;
      }

  </style>

  </head>
  <body style='background-image: linear-gradient(white 10%, #a38f8f   ) ;' >
      {% block foo %}
      {% include "app2/main_index.html" %}
     {% endblock %}

     <p class='main_heading' style='margin-left: 270px;'>Login here</p>

     <div class="container" style='width: 60%;'>
        <div class="jumbotron" tyle='background-image: linear-gradient( #dac0c0 , rgb(255, 255, 255)   ) ; '>
          
    <form style='display: table;' method="post" action="{% url 'app1:login' %}" >
              {% csrf_token %}
              <!-- {# A more "HTML" way of creating the login form#} -->
            
            <p style='display: table-row'>
              <label  class="text_label" for="username">Username :</label>
              <span  style='margin-left:px; visibility: hidden;'>:</span>

              <input  class="text_field" type="text" name="username" placeholder="Username">
            </p>
            <p style='display: table-row'>
              <label  class="text_label" for="password">Password :</label>
              <span  style='margin-left:px; visibility: hidden;'>:</span>
              <input  class="text_field"  type="password" name="password" placeholder="Password">
            </p>
              <input  class='pricingTable-firstTable_table__getstart submitbutton'   style='color: rgb(54, 47, 47);'  type="submit" name="" value="Login">
            
    </form>



 



    </div>
      </div>

      {% if failed_login %}
      <p class='main_heading'>LOGIN FALIED : INVALID CREDENTIALS</p>

      <audio controls autoplay style='visibility: hidden;'>
          <source  src="{% static 'sound1.mp3' %}" type="audio/mpeg">
        </audio>

      {%endif%}

        
      
  </body>
</html>

Fima/templates/app1/search.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <title>Add User</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- remove this for good font -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- remove this for good font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel = 'stylesheet' href ="{% static "css/user_profile.css" %}"/> 
    <link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 

    <script>
          ('.toast').toast('show');
    </script>
  </head>
  <body style='background-image: linear-gradient(white 10%, #ffffff , #ffffff   ) ; '>
      {% block foo %}
      {% include "app2/main_index.html" %}
	 {% endblock %}
	 
	 <p class='main_heading' >Search User</p>

	 <div class='initial_form'>
		<form action="{% url 'app1:search' %}" method="POST" value="{{request.GET.q}}">
			{% csrf_token %}
			<input class='search_bar' type="text" name="q" values="{{request.GET.q}}" placeholder="Search Here">
			<input class='pricingTable-firstTable_table__getstart' style='width:150px; height:60px; padding-top: 0px; ' type="submit" name="submit" value="search">
		</form>
	</div>
	 
	 {% if result %}
		 <h2  class='result_out' style='margin-left: 350px;' >Results for <b>{{ request.GET.q }}</b> <b>{{result.email}}</b></h2>
	
		 {% if is_friend is not True %}
		 <div class='initial_form'>
			 <form action="{% url 'app1:search' %}" method="POST" >
				 {% csrf_token %}
				 <input class='pricingTable-firstTable_table__getstart' style='width:350px; height:60px; padding-top: 0px; '  type="submit" name="add" value='Click To Add Friend'>
			 </form>
		</div>
		 {% else %}
		 <br>
		 <div style='width: 100%; border-top: 4px solid rgb(206, 221, 178);'></div>

			 <h3 class='normal_text' >This User is already a Friend</h3>
		 {% endif %}
	 
	 
	 {% elif success %}
	 <br>

	 	<div style='width: 100%; border-top: 4px solid rgb(206, 221, 178);'></div>
			 
		 <h2 class='result_out'>Friend is added Succesfully</h2>	
	 
	 {% else %}
	 <br>
	 <div style='width: 100%; border-top: 4px solid rgb(206, 221, 178);'></div>

		 <h2 class='result_out'>No Search Result</h2>	
	 {% endif %}

	 
  </body>

  
</html>

Fima/templates/app1/show_profile.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <title>Notifications</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>


    <!-- remove this for good font -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- remove this for good font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel = 'stylesheet' href ="{% static "css/user_profile.css" %}"/> 
    <link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 
    <link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Amatic SC' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Advent Pro' rel='stylesheet'>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

  </head>
  <body style='background-image: linear-gradient(white 10%, #ffffff , #ffffff   ) ; '>
    
      {% block foo %}
      {% include "app2/main_index.html" %}
     {% endblock %}
     

     

            
              
        <div class='row' style='height:100px;'>

            <div class='col-sm-6'>
              <div class="w3-card-4" style='width:500px; margin-left: 100px; margin-bottom: 100px;' >
                  <img style='width:100%' src="{{user_info.profile_pic.url}}" alt="ProfilePic">
  
              </div>
            </div>
  
  
            <div class='col-sm-6'>
              <div class="w3-card-4" style='width:60%; margin-left: 100px; margin-bottom: 10px; height:300%;' >
                  <header class="w3-container w3-blue">
                    <h1>{{ user_info.name }}</h1>
                  </header>
              
                  <div class="w3-container">
                      <p  class="some_text" style='font-size:30px; font-weight: normal;' >{{ user.email }}</p>
                      <p class="some_text" style='font-size:40px;font-weight: normal;'> {{ user_info.dob }}</p>
                      <p class="some_text" style='font-size:40px;font-weight: normal;'> {{ user_info.phone_number}}</p>  
                      <p class="some_text" style='font-size:40px;font-weight: normal;'> {{ user_info.user_address }}</p>               
                    </div>
              
                  <footer class="w3-container w3-blue">
                    <h5>{{user_info.gender}}</h5>
                    
                  </footer>
                </div>
  
                <form action="{% url 'app1:profile' %}">
                    <input  href='' class="pricingTable-firstTable_table__getstart" type="submit" value="Edit profile" 
                    style='font-weight:bold; font-size:20px; background-color: rgb(98, 245, 40); color:black; margin-bottom: 20px; width: 50%;font-family:  Advent Pro; margin-left: 100px;'
                    >
  
                </form>
                
                <form action="{% url 'app1:delete' %}">
                    <input  href='' class="pricingTable-firstTable_table__getstart" type="submit" value="Delete Account" 
                     style='font-weight:bold; font-size:20px; background-color: rgb(245, 115, 40); color:black; margin-bottom: 50px; width: 50%;font-family:  Advent Pro; margin-left: 100px;'>
  
                </form>
  
  
              </div>
  
          </div>



        
      
  </body>
</html>

Fima/templates/app1/special.html
<!DOCTYPE html>
<html>
<head>
	<title>special</title>
</head>
<body>
	<h1>Special Page</h1>

</body>
</html>