Fima/Fima/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Fima import settings
urlpatterns = [
    path('admin/', admin.site.	urls),
    path('',views.index,name='index'),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fima/app1/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
app_name='app1'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('special',views.special,name='special'),
    path('logout',views.user_logout,name='logout'),
    path('search',views.user_search,name='search'),
    path('transaction',views.make_transaction,name='transaction'),
    path('profile',views.user_profile,name='profile'),
    path('viewprofile',views.user_profile_view,name='viewprofile'),
    path('notification',views.show_notification,name='notification'),
    path('delete',views.delete_account,name='delete'),
]

Fima/app2/urls.py
from django.contrib import admin
from django.urls import path,include
from app2 import views
app_name='app2'


urlpatterns = [
    path('home',views.home,name='home'),
    path('all_trans',views.all_trans,name='all_trans'),
    path('history',views.history,name='history'),
    path('settle_trans',views.settle_trans,name='settle_trans'),

]

Fima/app2/models.py
from django.db import models

# Create your models here.

Fima/app2/views.py
from django.shortcuts import render
from app1.models import CurrentTransaction,UserProfileInfo,TransactionHistory,Friends
from app1.views import add_notification,notification_count
from collections import defaultdict
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from datetime import date
# Create your views here.

passed_email = ""


def history(request):
    current_user = request.user
    curr_user_email = str( current_user.get_username() ) #got current user
    his_record = TransactionHistory.objects.order_by('date')
    
    dict_to_pass = {'his_record':his_record , 'curr_user':curr_user_email}
    return render(request,'app2/history.html',dict_to_pass)    


def find_required_email(email):
    required_user  = User.objects.filter(email = email)[0]
    return required_user

def settle_trans(request):
    current_user = request.user
    curr_user_email = str( current_user.get_username() ) #got current user
    curr_trans = CurrentTransaction.objects.order_by('tdate')
    his_trans = TransactionHistory.objects.order_by('date')


    if request.method == 'POST':
        search_id = request.POST.get('friend_id')
        passed_email = search_id
        print(passed_email)
        # pass all transactions from CurrentTransaction to TransactionHistory for that specific user
        # print(len(curr_trans))
        for trans in curr_trans:
            # print(trans)
            if str(trans.user_id1) == curr_user_email:
                if str(trans.user_id2) == passed_email:
                    his = TransactionHistory.objects.get_or_create(user_id1 = trans.user_id1 , user_id2 = trans.user_id2 ,
                    date= trans.tdate , Amount = trans.amount , lent = trans.lent , borrowed = trans.lent , 
                    Desc = trans.desc)[0]
                    his.save()
                    # print(trans.desc)
                    req_email = find_required_email(passed_email)
                    CurrentTransaction.objects.filter( user_id1 = request.user , user_id2 = req_email  ).delete()

            if str(trans.user_id1) == passed_email:
                if str(trans.user_id2) == curr_user_email:
                    his = TransactionHistory.objects.get_or_create(user_id1 = trans.user_id1 , user_id2 = trans.user_id2,
                    date= trans.tdate , Amount = trans.amount , lent = trans.lent , borrowed = trans.lent , 
                    Desc = trans.desc)[0]  
                    his.save()
                    req_email = find_required_email(passed_email)
                    CurrentTransaction.objects.filter( user_id1 = req_email , user_id2 =  request.user  ).delete()
    # adding notifications
    message1 = curr_user_email + " has settled all expenses on " + str(date.today())
    message2 = "you have settled tranctions with " + passed_email + " on " + str(date.today())
    required_e = User.objects.filter(email = passed_email)[0]

    add_notification(request.user,message2)
    add_notification(required_e,message1)

    return render(request,'app2/all_trans.html')    




def all_trans(request):

    current_user = request.user
    curr_user_email = str( current_user.get_username() ) #got current user
    trans_record = CurrentTransaction.objects.order_by('tdate')

     # FOR POST METHOD
    if request.method == 'POST':
        search_id = request.POST.get('friend_id')
        passed_email = search_id

        trans_record = {'trans_record':trans_record , 'curr_user':curr_user_email,'required_email':passed_email,'combined_email':[curr_user_email,passed_email]}
        return render(request,'app2/all_trans.html',trans_record)    
    else:
        return render(request,'app2/all_trans.html')    



    # current_user = request.user
    # curr_user_email = str( current_user.get_username() ) #got current user
    # trans_record = CurrentTransaction.objects.order_by('tdate')
    # print("somehitn")
    # print(passed_email)
    # trans_record = {'trans_record':trans_record , 'curr_user':curr_user_email,'required_email':passed_email}
    # return render(request,'app2/all_trans',trans_record)    
    



def home(request):  
    print("notification count="+notification_count(request.user))
    current_user = request.user
    curr_user_email = str( current_user.get_username() ) #got current user
    all_details = {'pos':0 ,'neg':0  ,'total':0 ,'pos_ratio':0 ,'nag_ratio':0}
    # two final dict for passing to template
    friends_amount = defaultdict(lambda: 0)
    friends_name = defaultdict(lambda: 'none') 

    # queried database
    trans_record = CurrentTransaction.objects.order_by('tdate')
    user_record = UserProfileInfo.objects.order_by('name')
    friends = Friends.objects.all()

    # storing record of all friends
    for f in friends:
        if str(f.user_id1) == curr_user_email:
            friends_name[str(f.user_id2)] = 'none'
            friends_amount[str(f.user_id2)] = 0
        elif str(f.user_id2) == curr_user_email:
            friends_name[str(f.user_id1)] = 'none'
            friends_amount[str(f.user_id1)] = 0


    all_user = list(user_record)
    all_trans = list(trans_record)

    # CODE TO CALCULATE NET AMOUNT
    for record in trans_record:
        if str(record.user_id1) == curr_user_email:
            friends_amount[ str(record.user_id2) ] += int(record.amount)
            all_details['pos'] +=  int(record.amount)
            # print(str(record.user_id2)+'test1')

        elif str(record.user_id2) == curr_user_email:
            # print(str(record.user_id1)+'test2')
            friends_amount[ str(record.user_id1) ] -= int(record.amount)
            all_details['neg'] +=  int(record.amount)
    all_details['total'] = (all_details['pos'] -  all_details['neg'])
    #percent of distribution
    try:
        all_details['pos_ratio'] =  int( all_details['pos'] / ( all_details['pos'] + all_details['neg']) ) *100
        all_details['neg_ratio'] =  int( all_details['neg'] / ( all_details['pos'] + all_details['neg']) ) *100
    except:
        None
    # DISPLAY USERNAME ISTEAD OF EMAIL
    for users in all_user:
        if friends_name[ str(users.user) ] == 'none'  :
            friends_name[ str(users.user) ] = users.name

    try:
        friends_name.pop(curr_user_email) # idk how current user was also getting added to the dict
        friends_name.pop(curr_user_email)
        friends_amount.pop(curr_user_email)
    except:
        None
    # for key,_ in friends_name.items():
    #     print(friends_name[key],friends_amount[key])
    
    # friends_name and friends_amount are two dict having email as key and name and amount as value 
    trans_dict = {'names': friends_name,'amount':friends_amount, 'TITLE':'HOME','curr_user':current_user.get_username() , 'all_details': all_details}

    # my_dict = {'insert_content':"hello I am from first app"}
    return render(request, 'app2/home.html',trans_dict)

Fima/templates/app2/all_trans.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_extra %}

<html lang="en" >
<head>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <meta charset="UTF-8">
  <title>TRANSACTIONS</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 
<link rel = 'stylesheet' href ="{% static "css/tables.css" %}"/> 

</head>
<body>

  <!-- navbar -->
  {% block foo %}
  {% include "app2/main_index.html" %}
 {% endblock %}

 <div class='shift_it' style='  margin:50px;
 margin-left: 100px;
 font-size: 40px;'>All Transactions with User {{required_email}} are here</div>
    <!-- navbar end -->


    <div class = "djangotwo"> 
            {% if trans_record %}
            <table style='margin-left: 100px; width: 80%; font-weight: bold;'>
                <thead>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;'>Amount : </th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;'>Date : </th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;' >Desc : </th>
                </thead>
                {%  for t in trans_record %}
                        <tr>
                    {% if  t|check_for_this_user_transaction:combined_email %}    
                        {% if t|find_trans:curr_user %}
                                <td style='color:rgb(255, 115, 0); font-size: 30px; '>{{t.amount}}</td>
                        {% else %}
                            <tr>
                                <td style = 'color:rgb(0, 255, 7); font-size: 30px;'>{{t.amount}}</td>
                        {%endif%}

                                <td style='color: rgb(133, 127, 187); font-size: 20px;'>{{t.tdate }}</td>
                                <td style='color: rgb(133, 127, 187); font-size: 20px;'>{{t.desc}}</td>
                            </tr>
                    {%endif%}
                {% endfor %}
            </table>
            {%endif%}
        
         </div>

          {% if required_email %} 
          {% if trans_record %}
              
            <!-- test -->
            <div>
                <form action="{% url 'app2:settle_trans' %}" method ="POST">
                    {%csrf_token%}
                    <input type ="hidden" name = "friend_id" value="{{required_email}}" />
                    <button  class="pricingTable-firstTable_table__getstart"  type="submit"  style='margin-left: 90px; width: 200px; color: rgb(66, 61, 61); font-weight: bold; font-size: 20px;'>SETTLE UP</button>
                </form>
            </div>  
            <!-- testend -->
            {%endif%}
          {% else %}
            <div>
                <div class='shift_it' style='  margin:50px;
                margin-left: 100px;
                font-size: 40px;'>No Transactions to Show</div>            </div>
          {%endif%}
            

</body>
</html>

Fima/templates/app2/history.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_extra %}

<html lang="en" >
<head>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <meta charset="UTF-8">
  <title>transaction History</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- <link rel = 'stylesheet' href ="{% static "css/general.css  " %}"/>  -->
<link rel = 'stylesheet' href ="{% static "css/tables.css" %}"/> 

</head>
<body>


    {% block foo %}
     {% include "app2/main_index.html" %}
    {% endblock %}
    <div class='shift_it' style='  margin:50px;
    margin-left: 100px;
    font-size: 40px;'>All settled transactions are here</div>

            {% if his_record|check_object_size:curr_user %}
            <table style=' margin-bottom:100px; margin-left: 100px; width: 80%; font-weight: bold;  table-layout: fixed;
            '>
                <thead >
                    <th style='color: rgb(47, 53, 65); font-size: 40px; width: 400px;    '>Friend</th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;' >Amount</th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;' >Status</th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px;' >Date</th>
                    <th style='color: rgb(47, 53, 65); font-size: 40px; width: 200px;  '>Desc</th>
                </thead>
                {%  for t in his_record %}
                        <tr>
                             

                    {% if  t|check_for_history_of_transaction:curr_user %}    
                                <td style='color: rgb(133, 127, 187); font-size: 30px;'>{{ t|return_the_friend:curr_user }}</td>
                        {% if t|find_trans:curr_user %}
                                <td style='color:rgb(255, 115, 0); font-size: 30px; '>{{t.Amount}}</td>
                                <td style='color:rgb(255, 115, 0); font-size: 30px;'>Borrowed</td>

                        {% else %}
                                <td style = 'color:rgb(0, 255, 7); font-size: 30px;'>{{t.Amount}}</td>
                                <td style = 'color:rgb(0, 255, 7); font-size: 30px;'>Lent</td>

                        {%endif%}

                                <td style='color: rgb(133, 127, 187); font-size: 20px;'> {{t.date }}</td>
                                <td style='color: rgb(133, 127, 187); font-size: 20px;' > {{t.Desc}}</td>
                            </tr>
                    {%endif%}
                    
                {% endfor %}
            </table>
            {%else%}
                <p style='font-size:50px; margin-left:90px; color:rgb(195, 78, 78)'>No transaction records found</p>
            {%endif%}
        

         


         

</body>
</html>

Fima/templates/app2/home.html
<!DOCTYPE html>

{% load staticfiles %}
{% load my_extra %}

<html lang="en" >
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <meta charset="UTF-8">
  <title>HOME</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- remove this for good font -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <!-- remove this for good font -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 

</head>
<body>

  <!-- test -->

  <!-- testend -->

  {% block foo %}
  {% include "app2/main_index.html" %}
 {% endblock %}

<!-- partial:index.partial.html -->
 
  <!-- dashboard -->
  <!-- <span  style='margin: 220px; font-size: 40px; color:black' >Total</span> 

  <span style='height:1000px; border-left: 4px solid rgb(0, 0, 0);'></span>
            
  <span  style='margin: 100px; font-size: 40px; color:rgb(0, 255, 0)'>Lent</span>   

  <span style='height:500px; border-left: 4px solid rgb(0, 0, 0);'></span>
  
  <span  style='margin: 100px; font-size: 40px; color:rgb(255, 115, 0)'>Borrowed</span><br> 
  <span style='margin: 220px; font-size: 40px; color:black'>1111</span>

  <span style='height:500px; border-left: 4px solid rgb(0, 0, 0);'></span>

   <span style='margin: 100px; font-size: 40px; color:rgb(0, 255, 0)'>222</span>

   <span style='height:500px; border-left: 4px solid rgb(0, 0, 0);'></span>

    <span style='margin: 100px; font-size: 40px; color: rgb(255, 115, 0)'>4444</span><br>  -->


  <!-- dashboard -->

<div class="pricingTable">
  <h2 class="pricingTable-title">FINANCIAL MANAGEMENT</h2>
  <h3 class="pricingTable-subtitle">Your Friends and Finances</h3>


  <table style='margin-left: 200px; width: 80%; font-weight: bold;text-align:center;'>
      <thead >
          {% if all_details|check_sign_for_color %}
          <th style=' color:  rgb(0, 255, 0); font-size: 40px; text-align:center;'>Total</th>
          {%else%}
          <th style=' color:rgb(255, 115, 0); font-size: 40px; text-align:center;'>Total</th>
          {%endif%}
          <th style='color: rgb(0, 255, 0); font-size: 40px; text-align:center;' >Lent</th>
          <th style='color: rgb(255, 115, 0); font-size: 40px;text-align:center;' >Borrowed</th>
      </thead>
      <tr>
        
        {% if all_details|check_sign_for_color %}
        <td style='color: rgb(0, 255, 0); font-size: 40px;'>{{ all_details|return_pos:'total'}}</td>
        {%else%}
        <td style='color: rgb(255, 115, 0); font-size: 40px;'>{{ all_details|return_pos:'total'}}</td>

        {%endif%}

        <td style='color: rgb(0, 255, 0); font-size: 40px;'>{{ all_details|value_of_key:'pos'}}</td>
        <td style='color: rgb(255, 115, 0); font-size: 40px;'>{{ all_details|value_of_key:'neg'}}</td>
      </tr>
  </table><br><br><br>
  
  {% if amount|checksize %}

  <ul class="pricingTable-firstTable">
        {%  for email in amount %}
        <li class="pricingTable-firstTable_table">
            <h1 class="pricingTable-firstTable_table__header">{{ names|value_of_key:email}}</h1>
            {% if amount|check_pos:email %}
            <p class="pricingTable-firstTable_table__pricing"><span style='color: rgb(0, 255, 0)'>₹</span><span style='color:rgb(0, 255, 0)'>{{ amount|return_pos:email}}</span><span>Month</span></p>

            {% else %}
            <p class="pricingTable-firstTable_table__pricing"><span style='color: rgb(255, 115, 0)'>₹</span><span style='color:rgb(255, 115, 0)'>{{ amount|return_pos:email}}</span><span>Month</span></p>
            {%endif%}

            <ul class="pricingTable-firstTable_table__options">
              <li>{{email}}</li>

            </ul>
            <!-- <div class="pricingTable-firstTable_table__getstart">View All Transactions</div> -->
            
            <!-- test -->
            <div>
            <form action="{% url 'app2:all_trans' %}" method ="POST">
                {%csrf_token%}
                <input type ="hidden" name = "friend_id" value="{{email}}" />
                <button  class="pricingTable-firstTable_table__getstart"  type="submit" >VIEW TRANSACTIONS</button>
            </form>
            </div> 

            <div>
                <form action="{% url 'app1:transaction' %}" method ="POST">
                    {%csrf_token%}
                    <input type ="hidden" name = "friend_id" value="{{email}}" />
                    <input  class="pricingTable-firstTable_table__getstart"  type="submit" name='show' value='ADD TRANSACTIONs'>
                </form>
                </div> 
            
            <!-- testend -->

          </li>
        {% endfor %}
        
    </ul>
  </div>

  {%else%}
  <p style='font-size:70px; margin-left:120px; color:rgb(195, 78, 78)'>No TRANSACTIONS records found</p>  
  {%endif%}
   




</body>
</html>

Fima/templates/app2/main_index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_extra %}

<html lang="en" >
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <meta charset="UTF-8">
  <title>HOME</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- remove this for good font -->

  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <!-- remove this for good font -->
  <link href='https://fonts.googleapis.com/css?family=Advent Pro' rel='stylesheet'>

  <link rel = 'stylesheet' href ="{% static "css/home_css.css" %}"/> 

  <style>

    .pricingTable-firstTable_table:nth-of-type(n):before {
      content: 'Your Friend';
      position: absolute;
      color: rgb(0, 0, 0);
      display: block;
      background-color: #3bbdee;
      text-align: center;
      right: 15px;
      top: -25px;
      height: 65px;
      width: 65px;
      border-radius: 50%;
      box-sizing: border-box;
      font-size: 10px;
      padding-top: 15px;
      text-transform: uppercase;
      letter-spacing: 0.13em;
      transition: all 0.8s ease;

    }


  html,body{
    font-family:Advent Pro;  
  }
  .noti_img{
    height:40px ;
    widows: 40px;
    position: absolute;
    right:0;
    font-size: 30px;
  }


   .rotating{
    height:40px ;
    widows: 40px;
    position: absolute;
    right:0;
    font-size: 30px;
    transition: transform 1s linear;
    transform-origin: center;
    transform-style: preserve-3D;
    
  }
  .rotating:hover{
    transform: rotateY(720deg);
    position: absolute;
    right:0;
    font-size: 30px;
    transition: 2s ease;
    background-color: rgb(250, 108, 108);
    border-radius: 30%;
  }

  .rotatings:not(hover){
    height:80px ;
    widows: 80px;
    transition: 1s ease;
  }
    

    </style>


</head>
<body>


  <!-- test -->

<!-- testend -->

  <!-- navbar -->
  <nav class="navbar navbar-default navbar-static-top navbar-expand-lg" >
      <div class="container">
        <ul class="nav navbar-nav" >

          <li><a  class="navbar-brand" href="{% url 'index' %}" style='width: 200px;'>
              <img class='navimg' src="{% static "default1.png" %}">
            </a></li>


          <!-- {# When user is logined#} -->
          {% if user.is_authenticated %}
          <li><a class="navbar-brand" href="{% url 'app2:home' %}">Home</a></li>

          <li><a class="navbar-link" href="{% url 'app1:search' %}">Add Friend</a></li>
          <li><a class="navbar-link" href="{% url 'app2:history' %}">Transaction History</a></li>
          <li><a class="navbar-link" href="{% url 'app1:viewprofile' %}">{{request.user.get_username}}</a></li>
          <li><a class="navbar-link" href="{% url 'app1:notification' %}">Notifications</a></li>
          <li><a class="navbar-link" href="{% url 'app1:logout' %}">Logout</a></li>
            <!-- if not logined  -->
            {% else %}
          <li><a class="navbar-link" href="{% url 'app1:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'app1:login' %}">Login</a></li>

          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- navbar end -->
    {% if user.is_authenticated %}
    <div >
     <a href='{% url 'app1:notification' %}'> <img  class="rotating" style='margin-right: 35px;' src={% static 'icon.png' %} > </a>
       <div class="noti_img" style='margin-right: 10px;' >{{ 'some'|get_no_of_notifications:request.user }}</div>
     </div>
     {% endif %}

      <!-- footer  -->
      <!-- <div class="footer" style='  position: fixed;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 1rem;
      background-image: linear-gradient( rgb(145, 155, 197) , rgb(255, 255, 255));
      text-align: center;
      font-weight: bold;
      color: black;'>Made by by <strong>Prateek & Saharsh. @All Rights Reserved.</strong>.</div> -->
      <!-- footer  -->



</body>
</html>